base_config: ./config/qin_config/
base_expid: QIN_variety_v12
dataset_id: MicroLens_1M_x1

dataset_config:
    MicroLens_1M_x1:
        data_root: ./data/
        data_format: parquet
        train_data: ./data/MicroLens_1M_x1/train.parquet
        valid_data: ./data/MicroLens_1M_x1/valid.parquet
        test_data: ./data/MicroLens_1M_x1/test.parquet
        item_info: ./data/MicroLens_1M_x1/item_info.parquet
        rebuild_dataset: False
        feature_cols:
            - {name: user_id, active: True, dtype: int, type: meta}
            - {name: item_seq, active: True, dtype: int, type: meta}
            - {name: likes_level, active: True, dtype: int, type: categorical, vocab_size: 11}
            - {name: views_level, active: True, dtype: int, type: categorical, vocab_size: 11}
            - {name: item_id, active: True, dtype: int, type: categorical, vocab_size: 91718, source: item}
            - {name: item_tags, active: True, dtype: int, type: sequence, max_len: 5, vocab_size: 11740, source: item}
            - {name: item_emb_d128, active: True, dtype: float, type: embedding, source: item, embedding_dim: 128}
        label_col: {name: label, dtype: float}

tuner_space:
    batch_size: [ 8192 ]
    embedding_regularizer: [2.e-4]
    embedding_dim: [128]
    learning_rate: [2.e-3]
    net_dropout: [0.1]
    batch_norm: True
    num_layers: [4]
    num_row: [3, 4]
